---
title: "STA5092Z Assignment 1"
author: "Tino Muzambi"
date: "`r Sys.Date()`"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Libraries

```{r}
#install.packages("tidyverse")
library(tidyverse)
```

# Read in data

```{r}
# A1 & A2
a12.2015 <- read.csv("./Data/A1_2_2015.csv") %>% as_tibble
a12.2016 <- read.csv("./Data/A1_2_2016.csv") %>% as_tibble
a12.2017 <- read.csv("./Data/A1_2_2017.csv") %>% as_tibble
a12.2018 <- read.csv("./Data/A1_2_2018.csv") %>% as_tibble
a12.2019 <- read.csv("./Data/A1_2_2019.csv") %>% as_tibble
a12.2020 <- read.csv("./Data/A1_2_2020.csv") %>% as_tibble
a12.2021 <- read.csv("./Data/A1_2_2021.csv") %>% as_tibble
a12.2022 <- read.csv("./Data/A1_2_2022.csv") %>% as_tibble

# B1
b1.2015 <- read.csv("./Data/B1_2015.csv") %>% as_tibble
b1.2016 <- read.csv("./Data/B1_2016.csv") %>% as_tibble
b1.2017 <- read.csv("./Data/B1_2017.csv") %>% as_tibble
b1.2018 <- read.csv("./Data/B1_2018.csv") %>% as_tibble
b1.2019 <- read.csv("./Data/B1_2019.csv") %>% as_tibble
b1.2020 <- read.csv("./Data/B1_2020.csv") %>% as_tibble
b1.2021 <- read.csv("./Data/B1_2021.csv") %>% as_tibble
b1.2022 <- read.csv("./Data/B1_2022.csv") %>% as_tibble

# B2
b2.2015 <- read.csv("./Data/B2_2015.csv") %>% as_tibble
b2.2016 <- read.csv("./Data/B2_2016.csv") %>% as_tibble
b2.2017 <- read.csv("./Data/B2_2017.csv") %>% as_tibble
b2.2018 <- read.csv("./Data/B2_2018.csv") %>% as_tibble
b2.2019 <- read.csv("./Data/B2_2019.csv") %>% as_tibble
b2.2020 <- read.csv("./Data/B2_2020.csv") %>% as_tibble
b2.2021 <- read.csv("./Data/B2_2021.csv") %>% as_tibble
b2.2022 <- read.csv("./Data/B2_2022.csv") %>% as_tibble
```

# Checking the data

```{r}
print("A1_2")
str(a12.2015)
str(a12.2016)
str(a12.2017)
str(a12.2018)
str(a12.2019)
str(a12.2020)
str(a12.2021)
str(a12.2022)

print("B1")
str(b1.2015)
str(b1.2016)
str(b1.2017)
str(b1.2018)
str(b1.2019)
str(b1.2020)
str(b1.2021)
str(b1.2022)

print("B2")
str(b2.2015)
str(b2.2016)
str(b2.2017)
str(b2.2018)
str(b2.2019)
str(b2.2020)
str(b2.2021)
str(b2.2022)
```
# Merge into one tibble

```{r}
# First rename StudentID variable to ID
a12.2015 <- a12.2015 %>%
  rename(ID = StudentID)
```

```{r}
undergraduate <- a12.2015
undergraduate <- bind_rows(list(undergraduate, a12.2016, a12.2017, a12.2018, a12.2019, a12.2020, a12.2021, a12.2022,
                                b1.2015, b1.2016, b1.2017, b1.2018, b1.2019, b1.2020, b1.2021, b1.2022,
                                b2.2015, b2.2016, b2.2017, b2.2018, b2.2019, b2.2020, b2.2021, b2.2022))
str(undergraduate)
```


# Look at top and bottom of data

```{r}
head(a12.2015)
tail(a12.2015)

head(b1.2020)
tail(b1.2020)

head(b2.2021)
tail(b2.2021)
```

# Check total number of observations

```{r}
dim(a12.2015)

dim(b1.2020)

dim(b2.2021)
```

# Create new grade column which has integers only

```{r}

convertGrades <- function(data) {
  return (data %>%
            mutate(Grade = ifelse(grepl("^[0-9]+$", Grade), as.integer(Grade), ifelse(Grade == "UP", 50, 0))))
}

# If string value in grade is an integer, convert to integer, else check if it's UP, if so, replace with 50, else replace with 0
a12.2015 <- convertGrades(a12.2015)
a12.2016 <- convertGrades(a12.2016)
a12.2017 <- convertGrades(a12.2017)
a12.2018 <- convertGrades(a12.2018)
a12.2019 <- convertGrades(a12.2019)
a12.2020 <- convertGrades(a12.2020)
a12.2021 <- convertGrades(a12.2021)
a12.2022 <- convertGrades(a12.2022)

b1.2015 <- convertGrades(b1.2015)
b1.2016 <- convertGrades(b1.2016)
b1.2017 <- convertGrades(b1.2017)
b1.2018 <- convertGrades(b1.2018)
b1.2019 <- convertGrades(b1.2019)
b1.2020 <- convertGrades(b1.2020)
b1.2021 <- convertGrades(b1.2021)
b1.2022 <- convertGrades(b1.2022)

b2.2015 <- convertGrades(b2.2015)
b2.2016 <- convertGrades(b2.2016)
b2.2017 <- convertGrades(b2.2017)
b2.2018 <- convertGrades(b2.2018)
b2.2019 <- convertGrades(b2.2019)
b2.2020 <- convertGrades(b2.2020)
b2.2021 <- convertGrades(b2.2021)
b2.2022 <- convertGrades(b2.2022)
```
